# Generated by Django 2.0.8 on 2018-08-11 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_list', models.TextField()),
                ('course_name', models.CharField(choices=[('MA8', 'Math 8'), ('SC10', 'Science 10'), ('PH11', 'Physics 11'), ('PH12', 'Physics 12')], max_length=20)),
                ('course_block', models.CharField(choices=[('11', 'Block 1-1'), ('12', 'Block 1-2'), ('13', 'Block 1-3'), ('14', 'Block 1-4'), ('21', 'Block 2-1'), ('22', 'Block 2-2'), ('23', 'Block 2-3'), ('24', 'Block 2-4')], max_length=10)),
                ('group_size', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first', models.CharField(default='John', max_length=30)),
                ('student_last', models.CharField(default='Smith', max_length=30)),
                ('nickname', models.CharField(default='JohnS', max_length=31)),
                ('attend', models.BooleanField(default=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Classroom')),
            ],
        ),
    ]
