# Generated by Django 2.0.8 on 2018-08-26 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20180825_1551'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together=set(),
        ),
    ]
