# Generated by Django 2.0.8 on 2018-08-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='user',
            new_name='teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
