# Generated by Django 2.0.8 on 2018-08-27 23:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0011_auto_20180827_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='group_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('course_block', 'teacher')},
        ),
    ]
