# Generated by Django 2.0.8 on 2018-08-27 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_auto_20180827_1638'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together=set(),
        ),
    ]
