# Generated by Django 2.0.8 on 2018-08-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0015_remove_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='group_size',
        ),
        migrations.AddField(
            model_name='classroom',
            name='grade',
            field=models.CharField(choices=[('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='8', max_length=2),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='course_name',
            field=models.CharField(choices=[('MA', 'Math'), ('SC', 'Science'), ('SS', 'Social Studies'), ('EN', 'English Language Arts'), ('AP', 'Applied Skills'), ('PE', 'Phys Ed'), ('ML', 'Modern Languages'), ('CE', 'Career Ed'), ('AR', 'Arts')], max_length=20),
        ),
    ]
