"""
Django settings for classroomtools project.

Generated by 'django-admin startproject' using Django 2.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

from project.settings.base import *
from decouple import config
import dj_database_url

DEBUG = False
INSTALLED_APPS += (
    # other apps for production site
)

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = config['general']['secretkey']
SECRET_KEY = config('SECRET_KEY')

ALLOWED_HOSTS = ['*']


# Application definition


# setup email
#EMAIL_HOST = config['emailconfig']['emailhost']
#EMAIL_HOST_USER = config['emailconfig']['username']
#EMAIL_HOST_PASSWORD = config['emailconfig']['password']
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_HOST_USER = config('EMAIL_USERNAME')
EMAIL_HOST_PASSWORD = config('EMAIL_PASSWORD')
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_PORT = config('EMAIL_PORT', cast=int)
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' 


WSGI_APPLICATION = 'classroomtools.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR,'db.sqlite3'),
        }
    }
db_from_env = dj_database_url.config()

DATABASES['default'].update(db_from_env)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

# compression and caching support from whitenoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

