# Generated by Django 2.2.9 on 2020-01-20 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_list', models.TextField()),
                ('course_name', models.CharField(choices=[('MA', 'Math'), ('SC', 'Science'), ('SS', 'Social Studies'), ('EN', 'English Language Arts'), ('AP', 'Applied Skills'), ('PE', 'Phys Ed'), ('ML', 'Modern Languages'), ('CE', 'Career Ed'), ('AR', 'Arts')], max_length=20)),
                ('course_block', models.CharField(choices=[('11', 'Block 1-1'), ('12', 'Block 1-2'), ('13', 'Block 1-3'), ('14', 'Block 1-4'), ('21', 'Block 2-1'), ('22', 'Block 2-2'), ('23', 'Block 2-3'), ('24', 'Block 2-4')], max_length=10)),
                ('grade', models.CharField(choices=[('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='8', max_length=2)),
                ('teacher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('course_block', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first', models.CharField(default='John', max_length=30)),
                ('student_last', models.CharField(default='Smith', max_length=30)),
                ('nickname', models.CharField(default='JohnS', max_length=31)),
                ('attend', models.BooleanField(default=True)),
                ('do_not_pick', models.BooleanField(default=False)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomizer.Classroom')),
            ],
        ),
    ]
